#relexpr.py
a=int(input("Enter Value of a:"))
b=int(input("Enter Value of b:"))
print("-"*50)
print("{}>{}={}".format(a,b,a>b))
print("{}>{}={}".format(b,a,b>a))
print("{}<{}={}".format(a,b,a<b))
print("{}<{}={}".format(b,a,b>a))
print("{}=={}={}".format(a,b,a==b))
print("{}!={}={}".format(a,b,a!=b))
print("{}>{}={}".format(a,b,a>b))
print("{}>={}={}".format(a,b,a>=b))
print("{}>={}={}".format(b,a,b>a))
print("{}>{}={}".format(a,b,a>b))
print("{}<={}={}".format(a,b,a<=b))
print("{}<={}={}".format(b,a,b>a))
print("-"*50)

